### ISSUE TITLE
Laser 310 FDC emulation

### ISSUE THREAD

**Issue by yuanb** [nippur72/laser310-emu#1]
Hi,

I'm not sure if this is the best place to send you a message. Please let me know if you have a better place, rather than logging an issue.

zzemu and I have been working on Laser 310 DI-40 interface and DD-20 floppy disk. After analyzing the DD20 recording. We came up with the most accurate FDC implementation so far. Please have a look on this file. It is much accurate than other implementations.
https://github.com/zzemu-cn/LASER310EMU/tree/master/src

And also, this is my Arduino UNO/Mega2560 DD-20 Emulator, it works with DI-40.
https://github.com/yuanb/dd20emu/tree/master/dd20emu

Sincerely,

Bill

**Comment by nippur72** [comment]
thanks this is very interesting as I have not coded the FDC part yet!

BTW, I wrote an FDC emulation for the Laser 500 which uses a different interface but on the same DD20 disk drive. It's a much simpler interface; the DOS implements the GCR encoding in software (cloned from Apple II).

The Arduino interface is also very interesting, we once tried to create a disk interface for the Laser 500 (for an Apple II disk drive) but we didn't succeed. So maybe we can get inspiration from your project and manage to complete it. Sadly, there are no disk drive interfaces for the Laser 500 that survived, so recreation is the only way.

My email is nino.porcino@gmail.com, you can also find me on the FB group "VZ 200 fans"

And if you want to have a look, my Laser 500 emulator is here: https://nippur72.github.io/laser500emu

Thank you for your message

**Comment by yuanb** [comment]
Sorry, I didn't realize you are in VZ200/VZ300 group as well. I will ping you from FB. Yes, I followed your Laser 500 emulator, amazing work!
